### ISSUE TITLE
Make Dispatchers implement some base Interface

### ISSUE THREAD

**Issue by semanticer** [dimsuz/diff-dispatcher#1]
For example in the sample code in your readme the ViewStateRendererDispatcher should implement some interface like "Dispatcher" with one method dispatch. I tried to build some helper wrapper code around your nice library but these generated classes are impossible to work with in some generic code.

**Comment by dimsuz** [comment]
I will think about this. Can you briefly describe why you need this? Do you create some kind of a base view-class which contains a dispatcher?

**Comment by semanticer** [comment]
Yeah, exactly. I wanted to create wrapper that would handle previousState for you and maybe also provide some helper methods for LiveData<ViewState> handling. It would be awesome if you could just write something like 

`livedataViewState.observe(this, superDispatcher)`

and everything was handled for you.

**Comment by dimsuz** [comment]
This makes sense!

I envision something like:

```kotlin
interface Dispatcher<VS> {
  fun dispatch(viewState: VS, previousViewState: VS?)
}

class GeneratedDispatcher : Dispatcher<ConcreteViewState> {
  override fun dispatch(viewState: ConcreteViewState, previousViewState: ConcreteViewState?)
}
```

I'll try to implement this soon! :)

**Comment by semanticer** [comment]
That's exactly it! I'm looking forward to this. Thanks
