### ISSUE TITLE
Не подхватываются геттеры свойств ViewState, имена которых начинаются на "is"

### ISSUE THREAD

**Issue by irinakarpenko** [dimsuz/diff-dispatcher#5]
`
private fun CharSequence.toGetterName(): CharSequence {
    return if (this.isGetterName()) this else "get${this.toString().capitalize()}"
}
private fun CharSequence.isGetterName() = this.startsWith("is") || this.startsWith("get")
`
Файл Processor, строчка 624

**Comment by dimsuz** [comment]
Дополнение: некорректно определяются getters для property вида "issueCount" - процессор ищет свойство с именем `sueCount` в данном случае.

**Comment by dimsuz** [comment]
Fixed in `v0.9.4`, see https://github.com/dimsuz/diff-dispatcher/releases
